import type { Metadata } from "next";
import "@fontsource/plus-jakarta-sans";
import "./globals.css";
import AuthProvider from "@/components/providers/AuthProvider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className="font-plus-jakarta-sans antialiased bg-white text-black min-h-screen"
        style={{ fontFamily: '"Plus Jakarta Sans Variable", sans-serif' }}
      >
        <AuthProvider>
          <main className="w-full min-h-screen flex flex-col">{children}</main>
          <Toaster position="top-right" richColors />
        </AuthProvider>
      </body>
    </html>
  );
}
